
/**
 * Global media storage URLs configuration
 */

const MEDIA_BASE_URL = "https://tuieldonbxswmopvyryx.supabase.co/storage/v1/object/public/";

export const MEDIA_URLS = {
  images: {
    earthDark: "https://unpkg.com/three-globe/example/img/earth-dark.jpg",
    earthTopology: "https://unpkg.com/three-globe/example/img/earth-topology.png",
    characters: {
      principal: `${MEDIA_BASE_URL}1.principal/1.principal.webp`,
      mecanico: `${MEDIA_BASE_URL}1.principal/2.mecanico.webp`,
      expedicionista: `${MEDIA_BASE_URL}1.principal/3.expedicionista.webp`,
    },
  },
  videos: {
    run: `${MEDIA_BASE_URL}fondo/persona%20corriendo.mp4`,
    transition: `${MEDIA_BASE_URL}fondo/fondo_transicion.mp4`,
  },
  models: {
    // No models found in App.tsx but reserved for future use
  },
  sounds: {
    // No static sounds found in App.tsx (generated by Gemini) but reserved for future use
  },
  textures: {
    noise: "https://grainy-gradients.vercel.app/noise.svg",
  },
  branding: {
    logo: `${MEDIA_BASE_URL}1.principal/logo_pentadev.webp`,
    background: "/images/bg2.jpg",
  }
};
