export const STORY_STEPS = [
  'REGISTRO 452: LA HUMANIDAD SE HA DETENIDO.',
  'ENTIDADES NO IDENTIFICADAS DETECTADAS EN EL PERÍMETRO.',
  'ESTADO CRÍTICO. EL ORDEN SOCIAL HA COLAPSADO.',
  'EJECUTANDO PROYECTO-X... 100% CARGADO.',
  'ESCANEO DE CONSTANTES VITALES EN CURSO...',
  'RESISTE. SOBREVIVE. PREVALECE.',
  'ENLACE ESTABLECIDO. BIENVENIDO AL SISTEMA.',
  'LOCALIZA UN REFUGIO. SOLICITA ACCESO PARA SER PARTE DE LA RESISTENCIA.',
]
